name: Auto_Assign

on:
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - opened

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: add reviewers by auto assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/config/auto_assign.yml'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
